---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      volumeMounts:
        - name: pvc
          mountPath: /var/lib/www/html
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: pvc
        readOnly: false
