---
# This is a sample configmap that helps define a Ceph configuration as required
# by the CSI plugins.

# Sample ceph.conf available at
# https://github.com/ceph/ceph/blob/master/src/sample.ceph.conf Detailed
# documentation is available at
# https://docs.ceph.com/en/latest/rados/configuration/ceph-conf/
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-encryption-kms-config
data:
  ceph.conf: |
    [global]
    fsid=3cc11bc3-7444-4ddb-9d21-7aabb7bb141f
    public_network = 192.168.10.0/24
    cluster_network = 192.168.10.0/24
    mon_initial_members = 192.168.10.31
    mon_host = 192.168.10.31
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx

  # keyring is a required key and its value should be empty
  keyring: |
