apiVersion: tekton.dev/v1
kind: Task
metadata:
 name: source-to-package
spec:
 params:
 - name: git-repo-url
   type: string
 workspaces:
  - name: source
    description: code storage
 steps:
  - name: fetch-from-source
    image: alpine/git:v2.32.0
    script: |
      git clone ${params.git-repo-url} ${workspaces.source.path}/source
  - name: build-to-package
    image: maven:3.8-openjdk-11-slim
    workingDir: ${workspaces.source.path}/source
    script: |
      mvn clean install
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
 name: s2p-demo
spec:
 params:
 - name: git-repo-url
   type: string
 workspaces:
 - name: source
 tasks:
 - name: source-to-package
   params:
   - name: git-repo-url
     value: ${params.git-repo-url}
   workspaces:
   - name: source
     workspace: source
   taskRef:
    name: source-to-package
