apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
 name: source-to-package
spec:
 pipelineRef:
  name: s2p-demo
 params:
 #- name: git-url
 - name: git-repo-url
   value: https://gitee.com/mageedu/spring-boot-helloWorld.git
 workspaces:
 - name: codebase
   volumeClaimTemplate:
    spec:
     accessModes:
     - ReadWriteOnce
     resources:
      requests:
       storage: 1Gi
     storageClassName: nfs-csi
