apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
  #labels: 
   #name: jenkins
spec:
  replicas: 1
  selector:
   matchLabels: 
    app: jenkins 
    #name: jenkins
  strategy:
   type: RollingUpdate
   rollingUpdate: 
    maxUnavailable: 1
    maxSurge: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
  template:
    metadata:
     labels: 
       app: jenkins 
       #name: jenkins
     annotations:
       blackbox_path: "/jenkins/login"
       blackbox_port: "8080"
       blackbox_scheme: "http"
    spec:
      securityContext:
       fsGroup: 1000
       runAsUser: 1000
      #nodeSelector:
       #k8s: master
      nodeName: worker-1
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: easzlab.io.local:5000/easzlab/jenkinsci/blueocean:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: httpport
          containerPort: 8080
          protocol: TCP
        - name: jnlpport
          containerPort: 50000
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: -Xmx512m -Xms512m
        - name: JENKINS_OPTS
          value: --prefix=/jenkins
        - name: JENKINS_ARGS
          value: --prefix=/jenkins
        resources:
         limits:
           cpu: 1000m
           memory: 1Gi
         requests:
           cpu: 500m
           memory: 512Mi
        livenessProbe:
         httpGet:
          path: /jenkins/login
          port: 8080
         initialDelaySeconds: 30
         periodSeconds: 10
         timeoutSeconds: 5
         failureThreshold: 3
        readinessProbe:
         httpGet:
          path: /jenkins/login
          port: 8080
         initialDelaySeconds: 30
         periodSeconds: 10
         timeoutSeconds: 5
         failureThreshold: 3
        volumeMounts:
        - name: jenkins
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins
        hostPath:
         path: /opt/jenkins 
         type: Directory
        #persistentVolumeClaim:
         #claimName: jenkins-pv-claim

      #  - name: docker
      #    mountPath: /run/docker.sock
      #volumes:
      #- name: docker
      #  hostPath: 
      #    path: /run/docker.sock
      #    type: ''
      #imagePullSecrets:
      #- name: harbor
